// Objective-C API for talking to wireproxykit Go package.
//   gobind -lang=objc wireproxykit
//
// File is generated by gobind. Do not edit.

#ifndef __Wireproxykit_H__
#define __Wireproxykit_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Start parses the wireproxy config text, brings up the WireGuard device and
spawns its routines ([http] proxy) on background goroutines, then returns.
Calling Start while already running tears the previous tunnel down first.
 */
FOUNDATION_EXPORT BOOL WireproxykitStart(NSString* _Nullable config, NSError* _Nullable* _Nullable error);

/**
 * Stop tears the tunnel down. Safe to call when not running.
 */
FOUNDATION_EXPORT void WireproxykitStop(void);

#endif
