
// Objective-C API for talking to the following Go packages
//
//	wireproxykit
//
// File is generated by gomobile bind. Do not edit.
#ifndef __WireProxyKit_FRAMEWORK_H__
#define __WireProxyKit_FRAMEWORK_H__

#include "Wireproxykit.objc.h"
#include "Universe.objc.h"

#endif
